services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: certif
      MARIADB_USER: certif_user
      MARIADB_PASSWORD: certif_pass
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      ADMIN_PASSWORD: "Probance123!"
    depends_on:
      - db

