services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: certif
      MARIADB_USER: certif_user
      MARIADB_PASSWORD: certif_pass
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      - ./db_schema:/db_schema:ro
      - ./app/version.txt:/opt/certif/app/version.txt:ro

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docs:/opt/certif/docs:ro
      - ./db_schema:/opt/certif/db_schema
    environment:
      ADMIN_PASSWORD: "Probance123!"
      APP_BASE_URL: "http://localhost:8080"
      SMTP_HOST: "smtp-gw.company.lan"
      SMTP_PORT: "25"
      SMTP_FROM_EMAIL: "certif@company.tld"
      SMTP_FROM_NAME: "Probance Certif Tool"
      SMTP_USE_TLS: "0"
    depends_on:
      - db

