services:
  db:
    image: mariadb:11
    entrypoint: ["/bin/bash", "/usr/local/bin/db-entrypoint.sh"]
    command: ["mariadbd"]
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: certif
      MARIADB_USER: certif_user
      MARIADB_PASSWORD: certif_pass
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      - ./db_schema:/db_schema:ro
      - ./db/db-entrypoint.sh:/usr/local/bin/db-entrypoint.sh:ro
      - ./db/migrate-on-start.sh:/usr/local/bin/migrate-on-start.sh:ro

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      ADMIN_PASSWORD: "Probance123!"
    depends_on:
      - db

