ALTER TABLE questions
  MODIFY COLUMN need VARCHAR(128) NOT NULL DEFAULT 'PONE',
  MODIFY COLUMN knowledge_required_csv VARCHAR(255) NULL;

ALTER TABLE package_rules
  MODIFY COLUMN need VARCHAR(128) NOT NULL;
