ALTER TABLE users
  MODIFY COLUMN role ENUM('USER','PROGRAM_MANAGER','TEAM_MANAGER','MANAGER','OWNER','ADMIN') NOT NULL DEFAULT 'USER';

UPDATE users
SET role = CASE
  WHEN role IN ('TEAM_MANAGER', 'MANAGER') THEN 'USER'
  WHEN role = 'PROGRAM_MANAGER' THEN 'OWNER'
  ELSE role
END;

ALTER TABLE users
  MODIFY COLUMN role ENUM('USER','OWNER','ADMIN') NOT NULL DEFAULT 'USER';
