ALTER TABLE users
  MODIFY COLUMN role ENUM('USER','MANAGER','TEAM_MANAGER','OWNER','ADMIN') NOT NULL DEFAULT 'USER';

UPDATE users
SET role = 'USER'
WHERE role IN ('MANAGER', 'TEAM_MANAGER');

ALTER TABLE users
  MODIFY COLUMN role ENUM('USER','OWNER','ADMIN') NOT NULL DEFAULT 'USER';
